name: Quick Check
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Pipeline is working!"
      - name: Say Secret
        run: echo "${{ secrets.MY_TEST_KEY }}" | base64 --decode
      - name: Print secret with spaces
        run: echo "${{ secrets.MY_TEST_KEY }}" | sed 's/./& /g'
